# Generated by Django 3.2.9 on 2022-07-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0004_alter_reels_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story',
            field=models.ImageField(upload_to='Story'),
        ),
    ]
