# Generated by Django 3.2.9 on 2022-10-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_address',
            field=models.CharField(default=' ', max_length=1024),
        ),
    ]
