# Generated by Django 3.2.9 on 2022-10-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0007_post_post_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(default=' ', max_length=1024),
        ),
    ]
