# Generated by Django 3.2.9 on 2022-10-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0009_post_is_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
    ]
