# Generated by Django 3.2.9 on 2022-10-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0011_alter_post_is_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story2',
            field=models.FileField(default='', upload_to='Story'),
        ),
    ]
