# Generated by Django 3.2.9 on 2022-10-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0012_story_story2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(default=' ', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_address',
            field=models.CharField(default=' ', max_length=1024, null=True),
        ),
    ]
