# Generated by Django 3.2.9 on 2022-10-20 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0013_auto_20221020_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='reels',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Instagram.profile'),
        ),
    ]
